use_frameworks!

target 'GitHistorySpaceLib_Example' do
  pod 'GitHistorySpaceLib', :path => '../'

  target 'GitHistorySpaceLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
